### ISSUE TITLE
Error when trying to run

### ISSUE THREAD

**Issue by nmountz** [yasoob/Reddit-Twitter-bot#3]
Hi I've been getting this error when trying to run the script. 

[bot] setting up connection with Reddit
Traceback (most recent call last):
  File "F:/Python Projects/Twitter Botter/Reddit Scrapper/reddit_bot.py", line 132, in <module>
    main()
  File "F:/Python Projects/Twitter Botter/Reddit Scrapper/reddit_bot.py", line 96, in main
    subreddit = setup_connection_reddit(subreddit_name)
  File "F:/Python Projects/Twitter Botter/Reddit Scrapper/reddit_bot.py", line 55, in setup_connection_reddit
    "monitoring %s" % (subreddit))
  File "C:\Python27\lib\site-packages\praw\reddit.py", line 104, in __init__
    self.config = Config(site_name or os.getenv('praw_site') or 'DEFAULT', **config_settings)
  File "C:\Python27\lib\site-packages\praw\config.py", line 64, in __init__
    self.custom = dict(Config.CONFIG.items(site_name), **settings)
  File "C:\Python27\lib\ConfigParser.py", line 347, in items
    raise NoSectionError(section)
ConfigParser.NoSectionError: No section: 'yasoob_python reddit-twitter posting appmonitoring youtubehaiku
`

any ideas?

**Comment by AdrielC** [comment]
Me too. 

NoSectionError: No section: 'yasoob_python reddit-twitter posting appmonitoring Showerthoughts'

I'm a little stuck there.
